### PR TITLE
Modify remove function to return a boolean.

### PR DESCRIPTION
**Pull request by schmarjames**
Modified remove function to return a boolean based on the success of
removing a key from the local storage. This could be a convenience syntax wise to simply check if data has been removed.

### CODE REVIEW

**Comment by bevacqua** [comment]
Is there a case when data is not removed?

**Comment by schmarjames** [comment]
If the data isn't removed it will return false. The localStorage function "getItem" will return null if the key doesn't exist. Anything else means that the key still exist and the function will return false.

In any case if the user passes a key that does exist in the local storage it will be removed. This is just a way to determine if the remove was successful. The function ls.remove('keyName') can be passed to an if/else conditional. Besides the documentation states that it will return a boolean yet it doesn't.

**Comment by bevacqua** [comment]
You didn't answer my question, though

**Comment by schmarjames** [comment]
The answer to your question is no.

**Pull request closed without merging**
